name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: ${{ secrets.DB_PORT }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kobulwidodo/talentgrowt-api:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_AWS }}
          username: ${{ secrets.USERNAME_AWS }}
          key: ${{ secrets.KEY_AWS }}
          script: |
            sudo docker pull kobulwidodo/talentgrowt-api:latest
            sudo docker container create --name go-app-talentgrowth -e DB_HOST=${{ secrets.DB_HOST }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_NAME=${{ secrets.DB_NAME }} -e DB_PORT=${{ secrets.DB_PORT }} -e JWT_KEY=${{ secrets.JWT_KEY }} -e DB_SSLMODE=${{ secrets.DB_SSLMODE }} -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_REGION=${{ secrets.AWS_REGION }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} -e BUCKET_NAME=${{ secrets.BUCKET_NAME }} -p 8080:8080 kobulwidodo/talentgrowt-api:latest
            sudo docker container start go-app-talentgrowth
